### PR TITLE
create function to convert values px in rem

### PR DESCRIPTION
**Pull request by lucianobarauna**
#68

### CODE REVIEW

**Comment by luiguild** [comment]
@ronalson what do you think about the name of this new variable?

**Comment by ronalson** [comment]
@luiguild we are using the `base` keyword for the colors variables defaults, so I guess this name is fine for now.

---

However, If I were to add something to the broader naming convention discussion, it would be that I'm not a huge fan of camel case on CSS :) But we are using it in other places.

**Comment by luiguild** [comment]
Totally agree @ronalson, so I will accept this contribution for now because I understand the intention and the value it can deliver to the lib and I will open an issue to change all vars from `camelCase` to `kebab-kase` in favor to keep a better readable CSS code

**Comment by luiguild** [comment]
@lucianobarauna is invited and welcome to join and help us with this next step too 😄

**Pull request merged**
